# 🏋️‍♂️ Phase 3: Mid-Term Drills (综合强化训练)

> **🎯 目标**: 在进入机器学习之前，通过**高强度代码练习**巩固肌肉记忆。
> **Status**: `Practical Focus`, `No Theory, Only Code`

---

## 1. NumPy 向量化突击 (Vectorization Blitz) ⚡️

**规则**: 禁止使用 `for` 循环！必须用 NumPy 的向量化操作。

In [5]:
import numpy as np

# 题目 1: 加权平均 (Weighted Average)
# 场景: 算出某班级的最终成绩。
# - scores: 每个学生的 [期中, 期末, 作业] 成绩
# - weights: 权重 [0.3, 0.5, 0.2]
# 任务: 算出一个 shape=(5,) 的数组，包含每个人的最终加权分。

scores = np.array([
    [80, 90, 85],   # Student A
    [70, 75, 80],   # Student B
    [90, 95, 90],   # Student C
    [60, 65, 70],   # Student D
    [85, 80, 90]    # Student E
])
weights = np.array([0.3, 0.5, 0.2])

# ✍️ Your Code Here (1 line)
final_scores = (scores * weights).sum(axis=1)
final_scores

array([[24. , 45. , 17. ],
       [21. , 37.5, 16. ],
       [27. , 47.5, 18. ],
       [18. , 32.5, 14. ],
       [25.5, 40. , 18. ]])

In [12]:
# 题目 2: 过滤离群值 (Outlier Filtering)
# 场景: 发现了一批异常的交易金额。
# 任务: 找出所有 Z-score 绝对值大于 2 的金额 (即偏离均值超过 2 个标准差)。
# 提示: abs((x - mean) / std) > 2

data = np.array([100, 102, 98, 105, 97, 200, 99, 101, 5, 98])

# ✍️ Your Code Here
outliers = data[np.abs((data - np.mean(data))/np.std(data)) >2]
outliers

array([200,   5])

In [22]:
# 题目 3: 广播修正 (Broadcasting Fix)
# 场景: 给 3 个学生的 4 门课分别加分。
# 问题: 也就是 (3, 4) 的矩阵加上 (4,) 的向量。这会报错吗？
# 任务: 如果直接相加报错，请用 .reshape() 修复它，或者确认它本身是否可以直接相加。

matrix = np.ones((3, 4))  # 3 students, 4 courses
bonus = np.array([1, 2, 3, 4]) # Bonus for each course

# ✍️ Your Code Here
result = np.array(matrix)*bonus
result

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

## 2. A/B Testing 实战突击 ⚔️

**规则**: 使用 `statsmodels` 解决实际问题。

In [28]:
import statsmodels.stats.api as sms
from statsmodels.stats.proportion import proportions_ztest

# 题目 4: 还要多少样本？ (Sample Size)
# 场景: 老板想把转化率从 20% 提升到 20.5% (微小提升)。
# 只有 0.5% 的绝对涨幅 (Absolute Lift)。这需要多少样本？(Power=0.8, Alpha=0.05)

p1 = 0.20
p2 = 0.205

# ✍️ Your Code Here
# 1. Calculate Effect Size (Cohen's h)
# 2. Calculate N
Effect_Size = sms.proportion_effectsize(p1, p2)

# 2. 算样本量
required_n = sms.NormalIndPower().solve_power(
    effect_size=Effect_Size, 
    power=0.8, 
    alpha=0.05, 
    ratio=1  # 实验组和对照组 1:1 分配
)

print(f"我们需要每组至少 {int(np.ceil(required_n))} 个样本。")

我们需要每组至少 101400 个样本。


In [31]:
# 题目 5: 真假显著 (Significance Test)
# 场景: 跑了一周实验。
# Group A: 10,000 人，500 转化。
# Group B: 10,000 人，550 转化。
# 任务: 这个提升 (10%) 是显著的吗？

count = np.array([550, 500])
nobs = np.array([10000, 10000])

# ✍️ Your Code Here
stats,p_val = proportions_ztest(count,nobs)
print(p_val)
p1 = 550/10000
p2 = 500/10000

# ✍️ Your Code Here
# 1. Calculate Effect Size (Cohen's h)
# 2. Calculate N
Effect_Size = sms.proportion_effectsize(p1, p2)

# 2. 算样本量
required_n = sms.NormalIndPower().solve_power(
    effect_size=Effect_Size, 
    power=0.8, 
    alpha=0.05, 
    ratio=1  # 实验组和对照组 1:1 分配
)

print(f"我们需要每组至少 {int(np.ceil(required_n))} 个样本。")

0.315024258838384
0.11291950622436135
我们需要每组至少 31218 个样本。


# -----------------------------------------------------------
# 📝 Part 3: 笔试必考手写题 (Written Exam Simulation)
# -----------------------------------------------------------
# 规则: 这一部分是 "闭卷考试"。
# 请尝试不看 Cheat Sheet，凭记忆补全下面的代码。
# (大厂笔试题经常考这种填空)


import statsmodels.stats.api as sms
from statsmodels.stats.proportion import proportions_ztest


In [ ]:
# 题目 6: 手写 Z-test 签名
# 场景: 给你 count=[125, 100], nobs=[1000, 1000]
# 任务: 填空
stat, pval = propotion_ztest(count, __nobs__________)


In [ ]:
# 题目 7: 手写 Power Calculation
# 场景: 算出 effect_size 后，算样本量
required_n = sms.NormalIndPower()._xxpower___________(
   effect_size=..., 
   power=0.8, 
   alpha=0.05, 
   ratio=1
)

In [ ]:
# 题目 8: NumPy 的 if-else (这是必考题)
# 场景: 把 data 里大于 100 的数变成 1，小于等于 100 的变成 0。
# 提示: 用 np.where
data = np.array([105, 98, 102])
# binary_data = np.__where__________(data > 100, 1, 0)